# Generated by Django 3.2.8 on 2021-11-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sex',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
