# Generated by Django 3.2.8 on 2021-11-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_age_player_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='price',
            new_name='age',
        ),
    ]
