# Generated by Django 3.2.8 on 2021-11-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_price_player_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='age',
            new_name='price',
        ),
    ]
