# Generated by Django 3.2.8 on 2021-12-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rename_age_player_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='love',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sex',
        ),
        migrations.AddField(
            model_name='player',
            name='qq',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='player',
            name='sign',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
