# Generated by Django 3.2.8 on 2021-12-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20211201_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=256)),
                ('price', models.IntegerField(blank=True)),
                ('describe', models.TextField(blank=True, max_length=256)),
            ],
        ),
    ]
