# Generated by Django 3.2.8 on 2021-12-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='web_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
