# Generated by Django 3.2.8 on 2021-12-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_goods_web_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='web_name',
            new_name='webname',
        ),
    ]
