# Generated by Django 3.2.8 on 2021-12-03 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_rename_web_name_goods_webname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.player'),
        ),
    ]
