# Generated by Django 3.2.8 on 2021-12-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_goods_belong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='belong',
        ),
    ]
